services:

  apisix:
      image: "apache/apisix:3.13.0-debian"
      container_name: circ-apisix
      restart: always
      volumes:
        - ./apisix-config/config.yaml:/usr/local/apisix/conf/config.yaml:ro
        #- ./data/certs:/data/certs:ro

      labels:
          - traefik.enable=true

          # === Public proxy (9080) ===
          - traefik.http.services.apisix-proxy.loadbalancer.server.port=9080
          - traefik.http.routers.apisix-proxy.rule=Host(`${APISIX_PUBLIC_DOMAIN}`)
          - traefik.http.routers.apisix-proxy.entrypoints=websecure
          - traefik.http.routers.apisix-proxy.tls=true
          - traefik.http.routers.apisix-proxy.tls.certresolver=myresolver
          - traefik.http.routers.apisix-proxy.service=apisix-proxy

          # === Admin API (9180) ===
          - traefik.http.services.apisix-admin.loadbalancer.server.port=9180
          - traefik.http.routers.apisix-admin.rule=Host(`${APISIX_ADMIN_DOMAIN}`)
          - traefik.http.routers.apisix-admin.entrypoints=websecure
          - traefik.http.routers.apisix-admin.tls=true
          - traefik.http.routers.apisix-admin.tls.certresolver=myresolver
          - traefik.http.routers.apisix-admin.service=apisix-admin

      depends_on:
        - etcd
      networks:
        - traefik


  etcd:
    
    image: bitnami/etcd:3.6.4
    container_name: circ-etcd
    restart: always
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_DATA_DIR: ETCD_DATA_DIR=/bitnami/etcd
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - traefik

networks:
  traefik:
    external: true

